operators:
  skadi:
    common_name: dyn_illust_char_1012_skadi2
    release_folder: ./release/{name}/
    source_folder: ./operator/{name}/extracted/
    target_folder: ./operator/{name}/
    use_skel: true
server:
  operator_folder: /operator/
  release_folder: ./release/
  template_folder: /template/
