operator:
  preview: preview.jpg
  project_json: project.json
  source_folder: ./operator/{name}/extracted/
  target_folder: ./operator/{name}/processed/
operators:
  chen: !include config/chen.yaml
  dusk: !include config/dusk.yaml
  dusk_everything_is_a_miracle: !include config/dusk_everything_is_a_miracle.yaml
  ling: !include config/ling.yaml
  nearl: !include config/nearl.yaml
  nian: !include config/nian.yaml
  nian_unfettered_freedom: !include config/nian_unfettered_freedom.yaml
  phatom_focus: !include config/phatom_focus.yaml
  rosmontis: !include config/rosmontis.yaml
  skadi: !include config/skadi.yaml
  skadi_sublimation: !include config/skadi_sublimation.yaml
  w: !include config/w.yaml
  w_fugue: !include config/w_fugue.yaml
  w_fugue_start: !include config/w_fugue_start.yaml # a special case here, no good way to handle
  specter: !include config/specter.yaml
server:
  operator_folder: ./operator/
  release_folder: ./release/
  template_folder: ./template/
