operator:
  preview: preview.jpg
  project_json: project.json
  source_folder: ./operator/{name}/extracted/
  target_folder: ./operator/{name}/processed/
  use_skel: true
operators:
  chen:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_1013_chen2
      fps: 60
      opacity: 100
      viewport_bottom: 1
      viewport_left: 0
      viewport_right: 0
      viewport_top: 1
    index.html:
      fallback_name: char_1013_chen2_2
      id: char_1013_chen2
      operator_logo: logo_rhodes_override
      title: 'Arknights: Ch''en/Chen the Holungday - 明日方舟：假日威龙陈'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: Ch''en/Chen the Holungday Live 2D\n明日方舟：假日威龙陈 Live
        2D\nThe model is extracted from game with Spine support.\n模型来自游戏内提取，支持Spine\nPlease
        set your FPS target in Wallpaper Engine > Settings > Performance > FPS\n请在
        Wallpaper Engine > 设置 > 性能 > FPS 下设置FPS\n\nLive preview on: https://arknights.halyul.dev/chen\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2564643862
  nearl:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_1014_nearl2
      fps: 60
      opacity: 30
      viewport_bottom: 0
      viewport_left: 2
      viewport_right: 3
      viewport_top: 10
    index.html:
      fallback_name: char_1014_nearl2_2
      id: char_1014_nearl2
      operator_logo: logo_kazimierz
      title: 'Arknights: Nearl the Radiant Knight - 明日方舟：耀骑士临光'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: Nearl the Radiant Knight Live 2D\n明日方舟：耀骑士临光 Live 2D\nThe
        model is extracted from game with Spine support.\n模型来自游戏内提取，支持Spine\nPlease
        set your FPS target in Wallpaper Engine > Settings > Performance > FPS\n请在
        Wallpaper Engine > 设置 > 性能 > FPS 下设置FPS\n\nLive preview on: https://arknights.halyul.dev/nearl\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2642836787
  nian:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_2014_nian
      fps: 60
      opacity: 30
      viewport_bottom: 5
      viewport_left: 2
      viewport_right: 2
      viewport_top: 3
    index.html:
      fallback_name: char_2014_nian_2
      id: char_2014_nian
      operator_logo: logo_sui
      title: 'Arknights: Nian - 明日方舟：年'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: Nian Live 2D\n明日方舟：年 Live 2D\nThe model is extracted
        from game with Spine support.\n模型来自游戏内提取，支持Spine\nPlease set your FPS target
        in Wallpaper Engine > Settings > Performance > FPS\n请在 Wallpaper Engine >
        设置 > 性能 > FPS 下设置FPS\n\nLive preview on: https://arknights.halyul.dev/nian\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2564642594
  rosmontis:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_391_rosmon
      fps: 60
      opacity: 100
      viewport_bottom: -1
      viewport_left: 0
      viewport_right: -14
      viewport_top: -38
    index.html:
      fallback_name: char_391_rosmon_2
      id: char_391_rosmon
      operator_logo: logo_rhodes_override
      title: 'Arknights: Rosmontis - 明日方舟：迷迭香'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: Rosmontis Live 2D\n明日方舟：迷迭香 Live 2D\nThe model is extracted
        from game with Spine support.\n模型来自游戏内提取，支持Spine\nPlease set your FPS target
        in Wallpaper Engine > Settings > Performance > FPS\n请在 Wallpaper Engine >
        设置 > 性能 > FPS 下设置FPS\n\nLive preview on: https://arknights.halyul.dev/rosmontis\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2642834981
  skadi:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_1012_skadi2
      fps: 60
      opacity: 30
      viewport_bottom: -12
      viewport_left: -5
      viewport_right: -10
      viewport_top: 0
    index.html:
      fallback_name: char_1012_skadi2_2
      id: char_1012_skadi2
      operator_logo: logo_egir
      title: 'Arknights: Skadi the Corrupting Heart - 明日方舟：浊心斯卡蒂'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: Skadi the Corrupting Heart Live 2Di\r\n明日方舟：浊心斯卡蒂 Live
        2Di\r\nThe model is extracted from game with Spine support.\r\n模型来自游戏内提取，支持Spine\r\nPlease
        set your FPS target in Wallpaper Engine > Settings > Performance > FPS\r\n请在
        Wallpaper Engine > 设置 > 性能 > FPS 下设置FPS\r\n\r\nLive preview on: https://arknights.halyul.dev/skadi\r\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2492307783
  w:
    _operator_settings.js:
      fallbackImage_height: 2048
      fallbackImage_width: 2048
      filename: dyn_illust_char_113_cqbw
      fps: 60
      opacity: 30
      viewport_bottom: 1
      viewport_left: 3
      viewport_right: -3
      viewport_top: 0
    index.html:
      fallback_name: char_113_cqbw_2
      id: char_113_cqbw
      operator_logo: logo_babel
      title: 'Arknights: W - 明日方舟：W'
      version: ${func:get_version()}
    project.json:
      description: 'Arknights: W Live 2D\n明日方舟：W Live 2D\nThe model is extracted from
        game with Spine support.\n模型来自游戏内提取，支持Spine\nPlease set your FPS target in
        Wallpaper Engine > Settings > Performance > FPS\n请在 Wallpaper Engine > 设置
        > 性能 > FPS 下设置FPS\n\nLive preview on: https://arknights.halyul.dev/w\nGithub:
        https://github.com/Halyul/aklive2d'
      title: ${var:index.html->title}
      ui_logo_opacity: ${var:_operator_settings.js->opacity}
      ui_logo_ratio: 61.8
      ui_operator_logo: 'true'
      ui_position_padding_bottom: ${var:_operator_settings.js->viewport_bottom}
      ui_position_padding_left: ${var:_operator_settings.js->viewport_left}
      ui_position_padding_right: ${var:_operator_settings.js->viewport_right}
      ui_position_padding_top: ${var:_operator_settings.js->viewport_top}
      workshopid: 2642838078
server:
  operator_folder: ./operator/
  release_folder: ./release/
  template_folder: ./template/
