akassets: 
  project_name: akassets
  url: https://akassets.halyul.dev
folder:
  auto_update_data: ./data/auto_update
  operator_data: ./data/operator/
  directory_src: directory
  showcase_src: showcase
  operator: ./operator/
  release: ./release/
  background: background
  music: music
  directory: _assets
  share: _share
  voice:
    main: voice
    sub:
      - name: jp
        lang: JP
      - name: cn
        lang: CN_MANDARIN
      - name: en
        lang: EN
      - name: kr
        lang: KR
      - name: custom
        lang: CUSTOM
share:
  title:
    zh-CN: "明日方舟："
    en-US: "Arknights: "
directory:
  title: AKLive2D
  voice: jp/CN_037.ogg
  error:
    files: !include config/_directory.yaml
    voice: CN_034.ogg
operators:
  chen: !include config/chen.yaml
  dusk: !include config/dusk.yaml
  dusk_everything_is_a_miracle: !include config/dusk_everything_is_a_miracle.yaml
  ling: !include config/ling.yaml
  nearl: !include config/nearl.yaml
  nian: !include config/nian.yaml
  nian_unfettered_freedom: !include config/nian_unfettered_freedom.yaml
  phatom_focus: !include config/phatom_focus.yaml
  rosmontis: !include config/rosmontis.yaml
  skadi: !include config/skadi.yaml
  skadi_sublimation: !include config/skadi_sublimation.yaml
  w: !include config/w.yaml
  w_wonder: !include config/w_wonder.yaml
  specter: !include config/specter.yaml
  gavial: !include config/gavial.yaml
  surtr_colorful_wonderland: !include config/surtr_colorful_wonderland.yaml
  lee_trust_your_eyes: !include config/lee_trust_your_eyes.yaml
  texas_the_omertosa: !include config/texas_the_omertosa.yaml
  nearl_relight: !include config/nearl_relight.yaml
  rosmontis_become_anew: !include config/rosmontis_become_anew.yaml
  passager_dream_in_a_moment: !include config/passager_dream_in_a_moment.yaml
  mizuki_summer_feast: !include config/mizuki_summer_feast.yaml
  chongyue: !include config/chongyue.yaml
  ling_it_does_wash_the_strings: !include config/ling_it_does_wash_the_strings.yaml
  pozemka_snowy_plains_in_words: !include config/pozemka_snowy_plains_in_words.yaml
  chen_ten_thousand_mountains: !include config/chen_ten_thousand_mountains.yaml
  specter_born_as_one: !include config/specter_born_as_one.yaml
  muelsyse: !include config/muelsyse.yaml
  kaltsit_remnant: !include config/kaltsit_remnant.yaml
  eyjafjalla_the_hvit_aska: !include config/eyjafjalla_the_hvit_aska.yaml
  goldenglow_summer_flowers_fa394: !include config/goldenglow_summer_flowers_fa394.yaml
  gavial_the_invincible_holiday_hd26: !include config/gavial_the_invincible_holiday_hd26.yaml
  ling_towering_is_cliff_of_nostalgia: !include config/ling_towering_is_cliff_of_nostalgia.yaml
  virtuosa: !include config/virtuosa.yaml
  texas_the_omertosa_wingbreaker: !include config/texas_the_omertosa_wingbreaker.yaml
  mwynar_w_dali: !include config/mwynar_w_dali.yaml
  reed_the_frame_shadow_curator: !include config/reed_the_frame_shadow_curator.yaml
  shu: !include config/shu.yaml
  lin_heavenly_mirage: !include config/lin_heavenly_mirage.yaml
  chongyue_alighting: !include config/chongyue_alighting.yaml
  wisadel: !include config/wisadel.yaml
  muelsyse_young_branch: !include config/muelsyse_young_branch.yaml
  skadi_the_corrupting_heart_red_countess: !include config/skadi_the_corrupting_heart_red_countess.yaml
  ines_under_the_flaming_dome: !include config/ines_under_the_flaming_dome.yaml
  silverash_never_melting_ice: !include config/silverash_never_melting_ice.yaml
  reed_the_frame_shadow_summer_flower: !include config/reed_the_frame_shadow_summer_flower.yaml
  eyjafjalla_the_hvit_aska_a_picnic_before_a_long_trip: !include config/eyjafjalla_the_hvit_aska_a_picnic_before_a_long_trip.yaml
  pepe: !include config/pepe.yaml
  nightingale_iakhu_of_flows: !include config/nightingale_iakhu_of_flows.yaml
  degenbrecher_the_shadow_of_dark_moon: !include config/degenbrecher_the_shadow_of_dark_moon.yaml