operator:
  preview: preview.jpg
  project_json: project.json
  source_folder: ./operator/{name}/extracted/
  target_folder: ./operator/{name}/processed/
operators:
  chen: !include config/chen.yaml
  dusk: !include config/dusk.yaml
  dusk_everything_is_a_miracle: !include config/dusk_everything_is_a_miracle.yaml
  ling: !include config/ling.yaml
  nearl: !include config/nearl.yaml
  nian: !include config/nian.yaml
  nian_unfettered_freedom: !include config/nian_unfettered_freedom.yaml
  phatom_placeholder: !include config/phatom_placeholder.yaml
  rosmontis: !include config/rosmontis.yaml
  skadi: !include config/skadi.yaml
  w: !include config/w.yaml
server:
  operator_folder: ./operator/
  release_folder: ./release/
  template_folder: ./template/
