filename: dyn_illust_char_1013_chen2_boc#6
logo: logo_rhodes_override
fallback_name: char_1013_chen2_boc#6
viewport_left: -1
viewport_right: 1
viewport_top: 2
viewport_bottom: -1
invert_filter: false
codename:
    zh-CN: 万重山 · 假日威龙陈
    en-US: Ten Thousand Mountains / Ch'en/Chen the Holungday
use_json: false
official_id: '202304659'
