filename: dyn_illust_char_2024_chyue_cfa#1
logo: logo_sui
fallback_name: char_2024_chyue_cfa#1
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 全能演员 · 重岳
  en-US: All-Round Actor / Chongyue
use_json: false
official_id: "202412452"
