filename: dyn_illust_char_1026_gvial2
logo: logo_rhodes_override
fallback_name: char_1026_gvial2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
codename: 
  zh-CN: 百练嘉维尔
  en-US: Gavial the Invincible
use_json: false
official_id: "202208258"