filename: dyn_illust_char_4087_ines_boc#8
logo: logo_babel
fallback_name: char_4087_ines_boc#8
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 燃烧天穹下 · 伊内丝
    en-US: Under the Flaming Dome / Ines
use_json: false
official_id: '202404087'
