filename: dyn_illust_char_003_kalts_boc#6
logo: logo_rhodes_override
fallback_name: char_003_kalts_boc#6
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
codename:
  zh-CN: 残余 · 凯尔希
  en-US: Remnant / Kal'tsit
use_json: false
official_id: "202304833"