filename: dyn_illust_char_322_lmlee_witch#3
logo: logo_lee
fallback_name: char_322_lmlee_witch#3
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename: 
  zh-CN: 手到牌来 · 老鲤
  en-US: Trust Your Eyes / Lee
use_json: false
official_id: "202210279"