filename: dyn_illust_char_4080_lin_nian#10
logo: logo_lungmen
fallback_name: char_4080_lin_nian#10
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 列瑶台 · 林
    en-US: Heavenly Mirage / Lin
use_json: false
official_id: '202401034'
