filename: dyn_illust_char_2023_ling_ncg#1
logo: logo_sui
fallback_name: char_2023_ling_ncg#1
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 崖高梦远 · 令
  en-US: Towering is Cliff of Nostalgia
use_json: false
official_id: "202308807"