filename: dyn_illust_char_249_mlyss
logo: logo_rhine
fallback_name: char_249_mlyss_2
viewport_left: 0
viewport_right: 0
viewport_top: 3
viewport_bottom: 2
invert_filter: true
codename:
  zh-CN: 缪尔赛思
  en-US: Muelsyse
use_json: false
official_id: "202304611"