filename: dyn_illust_char_249_mlyss_ambienceSynesthesia#6
logo: logo_rhine
fallback_name: char_249_mlyss_ambienceSynesthesia#6
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 漫步于黄金之梦 · 缪尔赛思
  en-US: Golden Reverie / Muelsyse
use_json: false
official_id: "202504900"
