filename: dyn_illust_char_179_cgbird_sightseer#1
logo: logo_followers
fallback_name: char_179_cgbird_sightseer#1
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 流辉 · 夜莺
    en-US: Iakhu of Flows / Nightingale
use_json: false
official_id: '202407435'
