filename: dyn_illust_char_1020_reed2_summer#17
logo: logo_dublinn
fallback_name: char_1020_reed2_summer#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 夏卉 FA075 · 焰影苇草
  en-US: Summer Flowers FA075 / Reed The Flame Shadow
use_json: true
official_id: "202407051"