filename: dyn_illust_char_1020_reed2_epoque#30
logo: logo_dublinn
fallback_name: char_1020_reed2_epoque#30
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 博物 · 焰影苇草
    en-US: Curator / Reed The Flame Shadow
use_json: false
official_id: '202401871'
