filename: dyn_illust_char_2025_shu_nian#11
logo: logo_sui
fallback_name: char_2025_shu_nian#11
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 春日宴 · 黍
  en-US: Spring Feast / Shu
use_json: false
official_id: "202501936"
