filename: dyn_illust_char_172_svrash_ambienceSynesthesia#4
logo: logo_kjerag
fallback_name: char_172_svrash_ambienceSynesthesia#4
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 不融冰 · 银灰
    en-US: Never-Melting Ice / SilverAsh
use_json: false
official_id: '202404066'
