filename: dyn_illust_char_1012_skadi2_iteration#2
logo: logo_egir
fallback_name: char_1012_skadi2_iteration#2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 红女爵 · 浊心斯卡蒂
  en-US: Red Countess / Skadi the Corrupting Heart
use_json: false
official_id: "202404008"
