filename: dyn_illust_char_1023_ghost2
logo: logo_abyssal
fallback_name: char_1023_ghost2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 归溟幽灵鲨
    en-US: Specter the Unchained
use_json: false
official_id: '202204284'
