filename: dyn_illust_char_1028_texas2_iteration#1
logo: logo_penguin
fallback_name: char_1028_texas2_iteration#1
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 破翼者 · 缄默德克萨斯
  en-US: Wingbreaker / Texas the Omertosa
use_json: false
official_id: "202310899"