filename: dyn_illust_char_1028_texas2_epoque#36
logo: logo_penguin
fallback_name: char_1028_texas2_epoque#36
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 幽兰秘辛 · 缄默德克萨斯
  en-US: Il Segreto Della Notte / Texas the Omertosa
use_json: false
official_id: "202410409"
