filename: dyn_illust_char_245_cello_sale#12
logo: logo_Laterano
fallback_name: char_245_cello_sale#12
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 无我唯识 · 塑心
  en-US: Diversity Oneness / Virtuosa
use_json: false
official_id: "202410467"
