filename: dyn_illust_char_1035_wisdel_sale#14
logo: logo_babel
fallback_name: char_1035_wisdel_sale#14
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
    zh-CN: 超新星 · 维什戴尔
    en-US: Supernova / Wisadel
use_json: false
official_id: '202504974'
