- key: build_char_128_plosis_epoque#3
  paddings:
    left: -120
    right: 150
    top: 10
    bottom: 0
- key: build_char_128_plosis
  paddings:
    left: -90
    right: 100
    top: 10
    bottom: 0