link: chen
date: 2021/08
type: operator
title: 'Arknights: Ch''en/Chen the Holungday - 明日方舟：假日威龙陈'
filename: dyn_illust_char_1013_chen2
logo: logo_rhodes_override
fallback_name: char_1013_chen2_2
viewport_left: 0
viewport_right: 0
viewport_top: 1
viewport_bottom: 1
invert_filter: false