date: 2021/08
filename: dyn_illust_char_1013_chen2
logo: logo_rhodes_override
fallback_name: char_1013_chen2_2
viewport_left: 0
viewport_right: 0
viewport_top: 1
viewport_bottom: 1
invert_filter: false
color: rgba(14, 126, 239, 0.85)
codename: 
  zh-CN: 假日威龙陈
  en-US: Ch'en/Chen the Holungday