filename: dyn_illust_char_1037_amiya3_sale#13
logo: logo_rhodes_override
fallback_name: char_1037_amiya3_sale#13
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
codename:
  zh-CN: 寰宇独奏 · 阿米娅
  en-US: Solo Around The World / Amiya
use_json: false
offical_id: "202412473"
