date: 2023/04
filename: dyn_illust_char_1013_chen2_boc#6
logo: logo_rhodes_override
fallback_name: char_1013_chen2_boc#6
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(6, 34, 129)
codename:
  zh-CN: 万重山 · 假日威龙陈
  en-US: Ten Thousand Mountains / Ch'en/Chen the Holungday