_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_1013_chen2
  fps: 60
  opacity: 100
  viewport_bottom: 1
  viewport_left: 0
  viewport_right: 0
  viewport_top: 1
  invert_filter: false
index.html:
  fallback_name: char_1013_chen2_2
  id: char_1013_chen2
  operator_logo: logo_rhodes_override
  title: 'Arknights: Ch''en/Chen the Holungday - 明日方舟：假日威龙陈'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: chen
type: operator
date: 2021/08