date: 2023/01
filename: dyn_illust_char_2024_chyue
logo: logo_sui
fallback_name: char_2024_chyue_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(255, 133, 34)
codename: 
  zh-CN: 重岳
  en-US: Chongyue