link: chongyue
type: operator
date: 2023/01
title: 'Arknights: Chongyue - 明日方舟：重岳'
filename: dyn_illust_char_1013_chen2
logo: logo_sui
fallback_name: char_1013_chen2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true