filename: dyn_illust_char_2024_chyue_nian#10
logo: logo_sui
fallback_name: char_2024_chyue_nian#10
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 何处栖 · 重岳
  en-US: Alighting / Chongyue
offical_id: "202401812"
