filename: dyn_illust_char_4116_blkkgt_witch#5
logo: logo_kjerag
fallback_name: char_4116_blkkgt_witch#5
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 暗月的影子 · 锏
  en-US: The Shadow Of The Dark Moon / Degenbrecher
use_json: false
offical_id: "202410426"
