date: 2021/02
filename: dyn_illust_char_2015_dusk
logo: logo_sui
fallback_name: char_2015_dusk_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(9, 212, 208)
codename: 
  zh-CN: 夕
  en-US: Dusk
portrait: null