date: 2022/01
filename: dyn_illust_char_2015_dusk_nian#7
logo: logo_sui
fallback_name: char_2015_dusk_nian#7
viewport_left: 10
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(78, 201, 187)
codename: 
  zh-CN: 染尘烟 · 夕
  en-US: Everything is a Miracle / Dusk