link: dusk
type: operator
date: 2021/02
title: 'Arknights: Dusk - 明日方舟：夕'
filename: dyn_illust_char_2015_dusk
logo: logo_sui
fallback_name: char_2015_dusk_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true