_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_2015_dusk_nian#7
  fps: 60
  opacity: 30
  viewport_bottom: 0
  viewport_left: 10
  viewport_right: 0
  viewport_top: 0
index.html:
  fallback_name: char_2015_dusk_nian%237
  id: char_2015_dusk_nian%237
  operator_logo: logo_sui
  title: 'Arknights: Everything is a Miracle / Dusk - 明日方舟：染尘烟·夕'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: dusk_everything_is_a_miracle
type: skin
date: 2022/01