link: dusk_everything_is_a_miracle
type: skin
date: 2022/01
title: 'Arknights: Everything is a Miracle / Dusk - 明日方舟：染尘烟·夕'
filename: dyn_illust_char_2015_dusk_nian#7
logo: logo_sui
fallback_name: char_2015_dusk_nian#7
viewport_left: 10
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true