filename: dyn_illust_char_1032_excu2_sale#12
logo: logo_Laterano
fallback_name: char_1032_excu2_sale#12
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 众志归一 · 圣约送葬人
  en-US: Allmind as one / Executor the Ex Foedere
use_json: false
offical_id: "202410488"
