filename: dyn_illust_char_1016_agoat2_epoque#34
logo: logo_Leithanien
fallback_name: char_1016_agoat2_epoque#34
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
codename:
  zh-CN: 远行前的野餐 · 纯烬艾雅法拉
  en-US: A Picnic Before A Long Trip / Eyjafjalla the Hvít Aska
use_json: true
offical_id: "202407072"
