filename: dyn_illust_char_1016_agoat2
logo: logo_Leithanien
fallback_name: char_1016_agoat2_2
viewport_left: 1
viewport_right: 0
viewport_top: 5
viewport_bottom: 5
invert_filter: true
codename:
  zh-CN: 纯烬艾雅法拉
  en-US: Eyjafjalla the Hvít Aska
offical_id: "202307865"