date: 2023/07
filename: 
logo: 
fallback_name: 
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(34, 187, 255)
codename:
  zh-CN: 纯烬艾雅法拉
  en-US: EYJAFJALLA THE HVÍT ASKA
