date: 2023/07
filename: 
logo: 
fallback_name: 
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(163, 220, 247)
codename:
  zh-CN: 悠然假日 HD26 · 百炼嘉维尔
  en-US: Holiday HD26 / Gavial the Invincible
