link: gavial
type: operator
date: 2022/08
title: 'Arknights: Gavial the Invincible - 明日方舟：百练嘉维尔'
filename: dyn_illust_char_1026_gvial2
logo: logo_rhodes_override
fallback_name: char_1026_gvial2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false