date: 2023/07
filename: 
logo: 
fallback_name: 
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgba(253, 188, 208, 0.97)
codename:
  zh-CN: 夏卉 FA394 · 澄闪
  en-US: SUMMER FLOWERS FA394 / Goldenglow
