filename: dyn_illust_char_1038_whitw2
logo: logo_chiave
fallback_name: char_1038_whitw2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 荒芜拉普兰德
  en-US: Lappland the Decadenza
use_json: false
offical_id: "202410440"
