link: lee_trust_your_eyes
type: skin
date: 2022/10
title: 'Arknights: Trust Your Eyes / Lee - 明日方舟：手到牌来·老鲤'
filename: dyn_illust_char_322_lmlee_witch#3
logo: logo_lee
fallback_name: char_322_lmlee_witch#3
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true