date: 2022/01
filename: dyn_illust_char_2023_ling
logo: logo_sui
fallback_name: char_2023_ling_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(15, 206, 216)
codename: 
  zh-CN: 令
  en-US: Ling
portrait: null