link: ling_it_does_wash_the_strings
type: skin
date: 2023/01
title: 'Arknights: It Does Wash the Strings / Ling - 明日方舟：濯缨 · 令'
filename: dyn_illust_char_2023_ling_nian#9
logo: logo_sui
fallback_name: char_2023_ling_nian#9
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true