link: mizuki_summer_feast
type: skin
date: 2022/12
title: 'Arknights: Summer Feast / Mizuki - 明日方舟：夏日餮宴·水月'
filename: dyn_illust_char_437_mizuki_sale#7
logo: logo_higashi
fallback_name: char_437_mizuki_sale#7
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true