date: 2022/12
filename: dyn_illust_char_437_mizuki_sale#7
logo: logo_higashi
fallback_name: char_437_mizuki_sale#7
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(156, 210, 246)
codename: 
  zh-CN: 夏日餮宴 · 水月
  en-US: Summer Feast / Mizuki
portrait: null