_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_437_mizuki_sale#7
  fps: 60
  opacity: 30
  viewport_bottom: 0
  viewport_left: 0
  viewport_right: 0
  viewport_top: 0
  invert_filter: true
index.html:
  fallback_name: char_437_mizuki_sale%237
  id: char_437_mizuki_sale%237
  operator_logo: logo_higashi
  title: 'Arknights: Summer Feast / Mizuki - 明日方舟：夏日餮宴·水月'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: mizuki_summer_feast
type: skin
date: 2022/12