date: 2023/04
filename: dyn_illust_char_249_mlyss
logo: logo_rhine
fallback_name: char_249_mlyss_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(146, 212, 143)
codename:
  zh-CN: 缪尔赛思
  en-US: Muelsyse
