date: 2023/04
filename: dyn_illust_char_249_mlyss
logo: logo_rhodes_override
fallback_name: char_249_mlyss_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(118, 165, 185)
codename:
  zh-CN: 缪尔赛思
  en-US: Muelsyse
