filename: dyn_illust_char_249_mlyss_boc#8
logo: logo_rhine
fallback_name: char_249_mlyss_boc#8
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 新枝 · 缪尔赛思
  en-US: Young Branch / Muelsyse
use_json: false
offical_id: "202404090"
