date: 2022/11
filename: dyn_illust_char_1014_nearl2_epoque#17
logo: logo_kazimierz
fallback_name: char_1014_nearl2_epoque#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(141, 213, 228)
codename: 
  zh-CN: 复现荣光 · 耀骑士临光
  en-US: Relight / Nearl