link: nearl
type: operator
date: 2021/11
title: 'Arknights: Nearl the Radiant Knight - 明日方舟：耀骑士临光'
filename: dyn_illust_char_1014_nearl2
logo: logo_kazimierz
fallback_name: char_1014_nearl2_2
viewport_left: 2
viewport_right: 3
viewport_top: 10
viewport_bottom: 0
invert_filter: true