_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_1014_nearl2_epoque#17
  fps: 60
  opacity: 30
  viewport_bottom: 0
  viewport_left: 0
  viewport_right: 0
  viewport_top: 0
  invert_filter: true
index.html:
  fallback_name: char_1014_nearl2_epoque%2317
  id: char_1014_nearl2%2317
  operator_logo: logo_kazimierz
  title: 'Arknights: Relight / Nearl - 明日方舟：复现荣光·耀骑士临光'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: nearl_relight
type: skin