date: 2020/01
filename: dyn_illust_char_2014_nian
logo: logo_sui
fallback_name: char_2014_nian_2
viewport_left: 2
viewport_right: 2
viewport_top: 3
viewport_bottom: 5
invert_filter: true
color: rgb(255, 48, 0)
codename: 
  zh-CN: 年
  en-US: Nian