link: nian_unfettered_freedom
type: skin
date: 2021/02
title: 'Arknights: Unfettered Freedom / Nian - 明日方舟：乐逍遥·年'
filename: dyn_illust_char_2014_nian_nian#4
logo: logo_sui
fallback_name: char_2014_nian_nian#4
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true