_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_2014_nian_nian#4
  fps: 60
  opacity: 30
  viewport_bottom: 0
  viewport_left: 0
  viewport_right: 0
  viewport_top: 0
  invert_filter: true
index.html:
  fallback_name: char_2014_nian_nian%234
  id: char_2014_nian_nian%234
  operator_logo: logo_sui
  title: 'Arknights: Unfettered Freedom / Nian - 明日方舟：乐逍遥·年'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: nian_unfettered_freedom
type: skin