filename: dyn_illust_char_2014_nian_cfa#1
logo: logo_sui
fallback_name: char_2014_nian_cfa#1
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 霹雳导演 · 年
  en-US: Thunderbolt Director / Nian
use_json: false
offical_id: "202412491"
