link: passager_dream_in_a_moment
type: skin
date: 2022/11
title: 'Arknights: Dream in a Moment / Passager - 明日方舟：今昔须臾之梦 · 异客'
filename: dyn_illust_char_472_pasngr_epoque#17
logo: logo_sargon
fallback_name: char_472_pasngr_epoque#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true