date: 2022/11
filename: dyn_illust_char_472_pasngr_epoque#17
logo: logo_sargon
fallback_name: char_472_pasngr_epoque#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(231, 166, 144)
codename: 
  zh-CN: 今昔须臾之梦 · 异客
  en-US: Dream in a Moment / Passager