link: phatom_focus
type: skin
date: 2022/04
title: 'Arknights: Focus / Phatom - 明日方舟：焦点·傀影'
filename: dyn_illust_char_250_phatom_sale#4
logo: logo_victoria
fallback_name: char_250_phatom_sale#4
viewport_left: 0
viewport_right: 0
viewport_top: 5
viewport_bottom: 1
invert_filter: true