date: 2022/04
filename: dyn_illust_char_250_phatom_sale#4
logo: logo_victoria
fallback_name: char_250_phatom_sale#4
viewport_left: 0
viewport_right: 0
viewport_top: 5
viewport_bottom: 1
invert_filter: true
color: rgb(158, 2, 2)
codename: 
  zh-CN: 焦点 · 傀影
  en-US: Focus / Phatom