link: rosmontis
type: operator
date: 2020/11
title: 'Arknights: Rosmontis - 明日方舟：迷迭香'
filename: dyn_illust_char_391_rosmon
logo: logo_elite
fallback_name: char_391_rosmon_2
viewport_left: 0
viewport_right: -14
viewport_top: -38
viewport_bottom: -1
invert_filter: true