link: rosmontis_become_anew
type: skin
date: 2022/11
title: 'Arknights: Become Anew / Rosmontis - 明日方舟：拥抱新生·迷迭香'
filename: dyn_illust_char_391_rosmon_epoque#17
logo: logo_elite
fallback_name: char_391_rosmon_epoque#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true