date: 2022/11
filename: dyn_illust_char_391_rosmon_epoque#17
logo: logo_elite
fallback_name: char_391_rosmon_epoque#17
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(116, 177, 222)
codename: 
  zh-CN: 拥抱新生 · 迷迭香
  en-US: Become Anew / Rosmontis
portrait: dyn_portrait_char_391_rosmon_epoque#17