date: 2020/11
filename: dyn_illust_char_391_rosmon
logo: logo_elite
fallback_name: char_391_rosmon_2
viewport_left: 0
viewport_right: -14
viewport_top: -38
viewport_bottom: -1
invert_filter: true
color: rgb(23, 210, 236)
codename: 
  zh-CN: 迷迭香
  en-US: Rosmontis