filename: dyn_illust_char_2025_shu
logo: logo_sui
fallback_name: char_2025_shu_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 黍
  en-US: Shu
use_json: false
offical_id: "202401025"
