link: skadi
type: operator
date: 2021/05
title: 'Arknights: Skadi the Corrupting Heart - 明日方舟：浊心斯卡蒂'
filename: dyn_illust_char_1012_skadi2
logo: logo_egir
fallback_name: char_1012_skadi2_2
viewport_left: -5
viewport_right: -10
viewport_top: 0
viewport_bottom: -12
invert_filter: true