link: skadi_sublimation
type: skin
date: 2022/05
title: 'Arknights: Sublimation / Skadi the Corrupting Heart - 明日方舟：升华·浊心斯卡蒂'
filename: dyn_illust_char_1012_skadi2_boc#4
logo: logo_egir
fallback_name: char_1012_skadi2_boc#4
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true