filename: dyn_illust_char_1012_skadi2_boc#4
logo: logo_egir
fallback_name: char_1012_skadi2_boc#4
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename: 
  zh-CN: 升华 · 浊心斯卡蒂
  en-US: Sublimation / Skadi the Corrupting Heart
offical_id: "202204205"