link: specter
type: operator
date: 2022/05
title: 'Arknights: Specter the Unchained - 明日方舟：归溟幽灵鲨'
filename: dyn_illust_char_1023_ghost2
logo: logo_abyssal
fallback_name: char_1023_ghost2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true