date: 2023/04
filename: dyn_illust_char_1023_ghost2_boc#6
logo: logo_abyssal
fallback_name: char_1023_ghost2_boc#6
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: false
color: rgb(140, 7, 7)
codename:
  zh-CN: 生而为一 · 归溟幽灵鲨
  en-US: Born as One / Specter the Unchained
