date: 2022/05
filename: dyn_illust_char_1023_ghost2
logo: logo_abyssal
fallback_name: char_1023_ghost2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgba(14, 124, 203, 0.86)
codename: 
  zh-CN: 归溟幽灵鲨
  en-US: Specter the Unchained