filename: dyn_illust_char_1023_ghost2_boc#6
logo: logo_abyssal
fallback_name: char_1023_ghost2_boc#6
viewport_left: -1
viewport_right: 1
viewport_top: 0
viewport_bottom: 1
invert_filter: true
codename:
  zh-CN: 生而为一 · 归溟幽灵鲨
  en-US: Born as One / Specter the Unchained
use_json: false
offical_id: "202304670"