link: texas_the_omertosa
type: operator
date: 2022/11
title: 'Arknights: Texas the Omertosa - 明日方舟：缄默德克萨斯'
filename: dyn_illust_char_1028_texas2
logo: logo_penguin
fallback_name: char_1028_texas2_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true