date: 2023/11
filename: dyn_illust_char_245_cello
logo: logo_Laterano
fallback_name: char_245_cello_2
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
color: rgb(189, 103, 7)
codename:
  zh-CN: 塑心
  en-US: Virtuosa
