date: 2020/05
filename: dyn_illust_char_113_cqbw
logo: logo_babel
fallback_name: char_113_cqbw_2
viewport_left: 3
viewport_right: -3
viewport_top: 0
viewport_bottom: 1
invert_filter: true
color: rgb(228, 54, 56)
codename: 
  zh-CN: W
  en-US: W
portrait: null