_operator_settings.js:
  fallbackImage_height: 2048
  fallbackImage_width: 2048
  filename: dyn_illust_char_113_cqbw_epoque#7
  fps: 60
  opacity: 30
  viewport_left: 0
  viewport_right: 0
  viewport_top: 1
  viewport_bottom: -4
  invert_filter: true
index.html:
  fallback_name: char_113_cqbw_epoque%237
  id: char_113_cqbw_epoque%237
  operator_logo: logo_babel
  title: 'Arknights: Fugue / W - 明日方舟：恍惚·W'
  version: ${func:get_version()}
project.json: !include config/_project.json.yaml
link: w_fugue
type: skin