link: w_fugue
type: skin
date: 2020/11
title: 'Arknights: Fugue / W - 明日方舟：恍惚·W'
filename: dyn_illust_char_113_cqbw_epoque#7
logo: logo_babel
fallback_name: char_113_cqbw_epoque#7
viewport_left: 0
viewport_right: 0
viewport_top: 1
viewport_bottom: -4
invert_filter: true