date: 2020/11
filename: dyn_illust_char_113_cqbw_epoque#7
logo: logo_babel
fallback_name: char_113_cqbw_epoque#7
viewport_left: 0
viewport_right: 0
viewport_top: 1
viewport_bottom: -4
invert_filter: true
color: rgba(0, 0, 0, 0.83)
codename: 
  zh-CN: 恍惚 · W
  en-US: Wonder / W