filename: dyn_illust_char_4121_zuole_nian#11
logo: logo_yan
fallback_name: char_4121_zuole_nian#11
viewport_left: 0
viewport_right: 0
viewport_top: 0
viewport_bottom: 0
invert_filter: true
codename:
  zh-CN: 少年游 · 左乐
  en-US: Youthful Journey / Zuo Le
use_json: false
offical_id: "202501927"
