name: Build release and push to CF Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

env:
  DO_NOT_TRACK: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Download Data
        run: pnpm run download:data
      - name: Build
        run: pnpm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: aklive2d
          directory: dist
          wranglerVersion: '3'
