name: Build release and push to Github

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Build all
        run: pnpm run build-all
      - name: Build directory
        run: pnpm run vite:directory:build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLEAR_GLOBS_FILE: ".gh-pages-clear-rules"
          SKIP_EMPTY_COMMITS: true
