name: Update

on:
  schedule:
    - cron: '30 10 * * *'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Update
        run: pnpm run update
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto update"
