name: Update charwords

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Use PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i
      - name: Update charwords
        run: pnpm run charwords:update
      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(charwords): auto update"